---

repos:
  - repo: https://github.com/polymathrobotics/polymath_code_standard
    rev: v2.1.2
    hooks:
      # Basic checks and fixes that apply to any text file and the git repository itself
      - id: polymath-general
      # Enforce and insert copyright headers in source code for the project's license
      - id: polymath-copyright
        args: [--license, Apache-2.0, --wildcard-copyright-org]
      # Specific languages
      - id: polymath-python
      - id: polymath-cpp
      - id: polymath-shell
      - id: polymath-cmake
      - id: polymath-docker
      - id: polymath-markdown
      - id: polymath-xml
      - id: polymath-yaml
      - id: polymath-toml
      - id: polymath-json
